import {PrismaClient} from '@prisma/client'; const prisma=new PrismaClient();
async function main(){ await prisma.user.upsert({where:{email:'admin@example.com'},update:{},create:{email:'admin@example.com',name:'Demo Admin',role:'ADMIN'}}); await prisma.user.upsert({where:{email:'teacher@example.com'},update:{},create:{email:'teacher@example.com',name:'Demo Teacher',role:'TEACHER'}}); const learner=await prisma.user.upsert({where:{email:'learner@example.com'},update:{},create:{email:'learner@example.com',name:'Demo Learner',role:'LEARNER',profile:{create:{gradeLevel:'8',goals:'Build algebra confidence'}}}});
await prisma.graphEdge.deleteMany(); await prisma.graphNode.deleteMany();
const course=await prisma.course.create({data:{title:'Algebra Foundations',description:'Adaptive path through variables, equations, and graphing basics.'}}); const mods=['Variables and Expressions','Equations','Graphing Basics']; const modules=[] as any[]; for(let i=0;i<mods.length;i++) modules.push(await prisma.module.create({data:{title:mods[i],order:i+1,courseId:course.id}}));
const topics=[['Variables',0],['Expressions',0],['Inverse Operations',1],['One-Step Equations',1],['Two-Step Equations',1],['Coordinate Plane',2]] as const; const topicRows=[] as any[]; for(let i=0;i<topics.length;i++) topicRows.push(await prisma.topic.create({data:{title:topics[i][0],order:i+1,moduleId:modules[topics[i][1]].id}}));
const los=[['ALG-VAR-001','Understand variables','Explain how letters can represent unknown or changing values.','UNDERSTAND',0],['ALG-EXP-001','Evaluate simple expressions','Substitute values into simple algebraic expressions.','APPLY',1],['ALG-EQ-001','Understand inverse operations','Explain how inverse operations undo each other.','UNDERSTAND',2],['ALG-EQ-002','Solve one-step equations','Solve one-step linear equations in one variable.','APPLY',3],['ALG-EQ-003','Solve two-step equations','Solve two-step linear equations in one variable.','APPLY',4],['ALG-GRAPH-001','Understand coordinate pairs','Interpret ordered pairs on the coordinate plane.','UNDERSTAND',5]] as const; const loRows:any={}; for(const lo of los) loRows[lo[0]]=await prisma.learningObjective.create({data:{code:lo[0],title:lo[1],description:lo[2],cognitiveLevel:lo[3] as any,estimatedMinutes:20,difficulty:lo[4]+1,topicId:topicRows[lo[4]].id}});
const concepts=['variable','expression','substitution','equation','inverse operation','equality','coordinate pair','x-axis','y-axis']; const conceptRows:any={}; for(const c of concepts) conceptRows[c]=await prisma.concept.create({data:{slug:c.replaceAll(' ','-'),title:c,description:`Core concept: ${c}`}});
const resTitles=['Intro to Variables','Evaluating Expressions Practice','Inverse Operations Explainer','Solving One-Step Equations Guide','Solving Two-Step Equations Guide','Coordinate Plane Basics']; for(let i=0;i<los.length;i++) await prisma.resource.create({data:{title:resTitles[i],type:'ARTICLE',content:`Short guided lesson for ${los[i][1]}.`,learningObjectiveId:loRows[los[i][0]].id}});
for(const code of Object.keys(loRows)){ await prisma.assessmentItem.create({data:{learningObjectiveId:loRows[code].id,type:'MULTIPLE_CHOICE',prompt:`Which choice best matches ${loRows[code].title}?`,choices:['A correct algebra idea','A random guess','Skip it'],correctAnswer:'A correct algebra idea',explanation:'Use the definition and structure.'}}); await prisma.assessmentItem.create({data:{learningObjectiveId:loRows[code].id,type:'TRUE_FALSE',prompt:`True or false: ${loRows[code].title} is part of Algebra Foundations.`,choices:['true','false'],correctAnswer:'true',explanation:'This LO is in the demo course.'}}); await prisma.learnerMastery.create({data:{learnerId:learner.id,learningObjectiveId:loRows[code].id}}); }
const node=async(type:any,entityId:string,label:string)=>prisma.graphNode.create({data:{type,entityId,label}}); await node('COURSE',course.id,course.title); for(const l of Object.values(loRows) as any[]) await node('LEARNING_OBJECTIVE',l.id,l.title); for(const c of Object.values(conceptRows) as any[]) await node('CONCEPT',c.id,c.title);
const nodes=await prisma.graphNode.findMany(); const n=(type:string,id:string)=>nodes.find(x=>x.type===type&&x.entityId===id)!; const dep=[['ALG-EXP-001','ALG-VAR-001'],['ALG-EQ-002','ALG-VAR-001'],['ALG-EQ-002','ALG-EQ-001'],['ALG-EQ-003','ALG-EQ-002']]; for(const [s,t] of dep) await prisma.graphEdge.create({data:{sourceNodeId:n('LEARNING_OBJECTIVE',loRows[s].id).id,targetNodeId:n('LEARNING_OBJECTIVE',loRows[t].id).id,type:'DEPENDS_ON'}}); for(const [s,t] of dep) await prisma.graphEdge.create({data:{sourceNodeId:n('LEARNING_OBJECTIVE',loRows[t].id).id,targetNodeId:n('LEARNING_OBJECTIVE',loRows[s].id).id,type:'UNLOCKS'}}); const maps:any={'ALG-VAR-001':['variable'],'ALG-EXP-001':['expression','substitution'],'ALG-EQ-001':['inverse operation'],'ALG-EQ-002':['equation','equality'],'ALG-EQ-003':['equation'],'ALG-GRAPH-001':['coordinate pair','x-axis','y-axis']}; for(const code in maps) for(const c of maps[code]) await prisma.graphEdge.create({data:{sourceNodeId:n('LEARNING_OBJECTIVE',loRows[code].id).id,targetNodeId:n('CONCEPT',conceptRows[c].id).id,type:'REQUIRES_CONCEPT'}}); console.log('Seeded Algebra Foundations');}
main().finally(()=>prisma.$disconnect());
